Only favicon in the <head> tag
TedGoas/Cerberus pull request #187
Opened 2018-07-06 02:00 UTC by douglasprofessional

2018-07-06 04:14 UTC, TedGoas commented
@douglasprofessional Hi, I'm a little confused why you submitted this. The docs site doesn't currently have a favicon. What would be the benefit to adding all these files?

2018-07-09 11:43 UTC, TedGoas commented
@douglasprofessional ping ☝️ just want to make sure you saw my previous comment.

2018-07-10 14:35 UTC, TedGoas requested changes
@douglasprofessional This repo doesn't get much mobile traffic and I'm not especially concerned with folks bookmarking this on their devices. In the interest of [keeping this simple](http://tedgoas.github.io/Cerberus/#contribute), I vote to start with a single `ico` favicon file to address browsers.

How does that sound? If you agree, would you like to modify this PR? Or would you like me to help?

2018-07-10 14:35 UTC, TedGoas commented on docs/index.html
> +  <link rel="shortcut icon" href="assets/favicon/favicon.ico" type="image/x-icon" />
@douglasprofessional I think the `ico` might be the only one we want.

Some context:
This repo doesn't get much mobile traffic and I'm not especially concerned with folks bookmarking this on their devices. In the interest of [keeping this simple](http://tedgoas.github.io/Cerberus/#contribute), I vote to start with a single `ico` favicon file to address browsers.

How does that sound? If you agree, would you like to modify this PR? Or would you like me to help?

2018-07-10 22:17 UTC, douglasprofessional commented
In this case, best to just leave only the line <link rel="shortcut icon" href="assets/favicon/favicon.ico" type="image/x-icon" />

You could change, ok?

2018-07-11 02:41 UTC, merged